AllCops:
  TargetRubyVersion: 2.3
Style/AsciiComments:
  Enabled: false
Style/Lambda:
  EnforcedStyle: literal
Style/LambdaCall:
  Enabled: false
Security/YAMLLoad:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
